play_media_condition = [
    "Start the music",
    "Start a music",
    "Play a song",
    "play a music",
    "play the music",
    "play the song",
    "Begin the video",
    "Put on some music",
    "Play that track",
    "Start the movie",
    "Begin playing the video",
    "Launch the playlist",
    "Resume the video",
    "Continue playing",
    "Start the media",
    "Resume the music",
    "Start playing",
    "Continue with the video",
    "continue the music",
    "continue the song",
]

stop_media_condition = [
    "Stop the music",
    "Stop a music",
    "Pause the song",
    "End the video",
    "Pause the playback",
    "Stop the movie",
    "Pause that track",
    "Pause the media",
    "Pause the video",
    "Stop playing",
    "End the song",
    "Pause the music",
    "Finish the video",
]

next_track_condition = [
    "Next track please",
    "Skip this song",
    "Skip to the next track",
    "Move to the next song",
    "Play the next track",
    "Skip this track",
    "Next song please",
    "Move forward to the next song",
    "Play the following track",
    "Skip to the next song",
    "Go to the next track",
    "Skip to the next one",
    "Move to the next music",
    "Next track in the queue",
    "Move forward in the playlist",
    "Play the upcoming track",
    "Skip to the next music",
]

previous_track_condition = [
    "Previous track please",
    "Go back to the previous track",
    "Move to the previous song",
    "Play the previous track",
    "Go back to the last track",
    "Previous song, please",
    "Go back to the song before",
    "Play the previous song",
    "Go to the previous track",
    "Move to the song before this one",
    "Play the preceding song",
    "Go back to the last song",
    "Move back in the playlist",
    "Play the last track",
    "Go to the previous song in the playlist",
    "Move back in the music",
    "Play the song before this one",
    "Go back to the previous music",
]

volume_up_condition = [
    "Increase the volume",
    "Turn the volume up",
    "Raise the volume",
    "Make it louder",
    "Volume up, please",
    "Boost the volume",
    "Increase sound",
    "Turn up the volume",
    "Raise the sound level",
    "Make it louder, please",
    "Volume increase",
    "Turn up the sound",
    "Raise the volume level",
    "Increase the audio",
    "Turn the sound up",
    "Raise the audio level",
    "Make it a bit louder",
    "Volume boost",
    "Crank up the volume",
    "Give me more volume",
]

volume_down_condition = [
    "Decrease the volume",
    "Turn the volume down",
    "Lower the volume",
    "Make it quieter",
    "Volume down, please",
    "Reduce the volume",
    "Decrease sound",
    "Turn down the volume",
    "Lower the sound level",
    "Make it quieter, please",
    "Volume decrease",
    "Turn down the sound",
    "Lower the volume level",
    "Decrease the audio",
    "Turn the sound down",
    "Lower the audio level",
    "Make it a bit quieter",
    "Volume reduction",
    "Crank down the volume",
    "Give me less volume",
]

capture_screen_condition = [
    "Take a screenshot",
    "capture this screenshot",
    "Capture my screen",
    "Capture the screen",
    "Capture a screen",
    "Grab a screenshot",
    "Grab the screenshot",
    "Record the screen",
    "Screenshot, please",
    "Save the screen image",
    "Snap the screen",
    "Screen capture, now",
    "Take a snapshot",
    "Capture this moment",
    "Grab the display",
    "Record this screen",
    "Screenshot the window",
    "Save the current view",
    "Snap a shot of this",
    "Capture the entire screen",
    "Take a picture of the screen",
    "Save what's on the screen",
    "Screenshot the active window",
    "Record what's happening",
]

capture_entire_screen_condition = [
    "entire screen",
    "Capture the whole screen",
    "Take a full screen screenshot",
    "Take a full screenshot",
    "Screenshot the entire display",
    "Record the entire screen",
    "Grab the full screen image",
    "Save everything on the screen",
    "Snap the whole display",
    "Full screen capture",
    "Take a screenshot of everything",
    "Capture the whole desktop",
    "Record the entire screen activity",
    "Screenshot the complete view",
    "Save the full screen image",
    "Snap the entire screen",
    "Full-screen capture, please",
    "Take a snapshot of the whole screen",
    "Capture the whole screen content",
    "Record everything on the screen",
    "Screenshot the whole window",
    "Save the entire screen view",
]

capture_specific_screen_condition = [
    "Snip this area",
    "Capture this region",
    "Use snipping tool here",
    "Snip a specific part",
    "Take a snippet of this",
    "Snipping tool for this spot",
    "Capture only this portion",
    "Use snip tool for this",
    "Snip the selected area",
    "Capture just this section",
    "Use snipping tool now",
    "Snip a part of the screen",
    "Capture the highlighted area",
    "Snipping tool, select here",
    "Grab this specific part",
    "Use snip tool on this",
    "Snip only this region",
    "Capture the marked area",
    "Snipping tool, focus here",
    "Snip just this part",
]

open_youtube_condition = [
    "Open YouTube",
    "Launch YouTube",
    "Go to YouTube",
    "Access YouTube",
    "Start YouTube",
    "Navigate to YouTube",
    "Open up YouTube",
    "Visit YouTube",
    "Load YouTube",
    "Run YouTube",
    "Pull up YouTube",
    "Open the YouTube app",
    "Head to YouTube",
    "Access the YouTube platform",
    "Go into YouTube",
    "Begin YouTube",
    "Run the YouTube application",
    "Launch the YouTube site",
    "Open the YouTube webpage",
    "Fire up YouTube",
]

open_facebook_condition = [
    "Open Facebook",
    "Launch Facebook",
    "Go to Facebook",
    "Access my Facebook",
    "Start Facebook",
    "Navigate to Facebook",
    "Visit Facebook",
    "Open up Facebook",
    "Load Facebook for me",
    "Bring up Facebook",
    "Take me to Facebook",
    "Access Facebook account",
    "Fire up Facebook",
    "Open my Facebook profile",
    "Show me Facebook",
    "Log into Facebook",
    "Go into Facebook",
    "Get me on Facebook",
    "Load up Facebook",
    "Access the Facebook app",
]

open_ig_condition = [
    "Open Instagram",
    "Launch Instagram",
    "Go to Instagram",
    "Access my Instagram",
    "Start Instagram",
    "Navigate to Instagram",
    "Visit Instagram",
    "Open up Instagram",
    "Load Instagram for me",
    "Bring up Instagram",
    "Take me to Instagram",
    "Access Instagram account",
    "Open my Instagram profile",
    "Show me Instagram",
    "Log into Instagram",
    "Go into Instagram",
    "Get me on Instagram",
    "Load up Instagram",
    "Access the Instagram app",
    "Open IG",
    "Launch IG",
    "Go to IG",
    "Access my IG",
    "Start IG",
    "Navigate to IG",
    "Visit IG",
    "Open up IG",
    "Load IG for me",
    "Bring up IG",
    "Take me to IG",
    "Access IG account",
    "Fire up IG",
    "Open my IG profile",
    "Show me IG",
    "Log into IG",
    "Go into IG",
    "Get me on IG",
    "Load up IG",
    "Access the IG app",
]

open_reddit_condition = [
    "Open Reddit",
    "Launch Reddit",
    "Go to Reddit",
    "Access my Reddit",
    "Start Reddit",
    "Navigate to Reddit",
    "Visit Reddit",
    "Open up Reddit",
    "Load Reddit for me",
    "Bring up Reddit",
    "Take me to Reddit",
    "Access Reddit account",
    "Fire up Reddit",
    "Open my Reddit profile",
    "Show me Reddit",
    "Log into Reddit",
    "Go into Reddit",
    "Get me on Reddit",
    "Load up Reddit",
    "Access the Reddit app",
]

open_github_condition = [
    "Open GitHub",
    "Launch GitHub",
    "Go to GitHub",
    "Access my GitHub",
    "Start GitHub",
    "Navigate to GitHub",
    "Visit GitHub",
    "Open up GitHub",
    "Load GitHub for me",
    "Bring up GitHub",
    "Take me to GitHub",
    "Access GitHub account",
    "Fire up GitHub",
    "Open my GitHub profile",
    "Show me GitHub",
    "Log into GitHub",
    "Go into GitHub",
    "Get me on GitHub",
    "Load up GitHub",
    "Access the GitHub app",
]

open_x_condition = [
    "Open Twitter",
    "Launch Twitter",
    "Go to Twitter",
    "Access my Twitter",
    "Start Twitter",
    "Navigate to Twitter",
    "Visit Twitter",
    "Open up Twitter",
    "Load Twitter for me",
    "Bring up Twitter",
    "Take me to Twitter",
    "Access Twitter account",
    "Open my Twitter profile",
    "Show me Twitter",
    "Log into Twitter",
    "Go into Twitter",
    "Get me on Twitter",
    "Load up Twitter",
    "Access the Twitter app",
    "Open X",
    "Launch X",
    "Go to X",
    "Access my X",
    "Start X",
    "Navigate to X",
    "Visit X",
    "Open up X",
    "Load X for me",
    "Bring up X",
    "Take me to X",
    "Access X account",
    "Open my X profile",
    "Show me X",
    "Log into X",
    "Go into X",
    "Get me on X",
    "Load up X",
    "Access the X app",
]
